#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_4_0 .top37.tNo64.t0 
    set site_4_0 $site_4_0
    set site_4_1 .top37.tNo64.t1 
    set site_4_0 .top37.tNo65.t0 
    set site_4_0 $site_4_0
    set site_4_1 .top37.tNo65.t1 
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 803x563+300+113
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1444 882
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Shamir Secret Sharing Demo"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    entry $top.ent42 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent42" "shareNum" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m43 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    label $top.lab46 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {No of Share} 
    vTcl:DefineAlias "$top.lab46" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Threshold 
    vTcl:DefineAlias "$top.lab47" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent48" "threshold" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab53 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Secret 
    vTcl:DefineAlias "$top.lab53" "Label3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but57 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Split 
    vTcl:DefineAlias "$top.but57" "Split" vTcl:WidgetProc "Toplevel1" 1
    button $top.but58 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Combine 
    vTcl:DefineAlias "$top.but58" "Combine" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent60 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent60" "secret" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo64 \
        -width 734 -height 166 -takefocus {} 
    vTcl:DefineAlias "$top.tNo64" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo64.t0 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo64.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo64 add .top37.tNo64.t0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image {} \
        -compound none -underline -1 
    set site_4_0  $top.tNo64.t0
    text $site_4_0.tex66 \
        -background white -font TkTextFont -foreground black -height 154 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 734 -wrap word 
    .top37.tNo64.t0.tex66 configure -font TkTextFont
    .top37.tNo64.t0.tex66 insert end text
    vTcl:DefineAlias "$site_4_0.tex66" "splitResult" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tex66 \
        -in $site_4_0 -x 0 -y 0 -width 734 -relwidth 0 -height 154 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo64.t1 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo64.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo64 add .top37.tNo64.t1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo64.t1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo65 \
        -width 734 -height 166 -takefocus {} 
    vTcl:DefineAlias "$top.tNo65" "TNotebook2" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo65.t0 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo65.t0" "TNotebook2_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo65 add .top37.tNo65.t0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image {} \
        -compound none -underline -1 
    set site_4_0  $top.tNo65.t0
    text $site_4_0.tex67 \
        -background white -font TkTextFont -foreground black -height 154 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 734 -wrap word 
    .top37.tNo65.t0.tex67 configure -font TkTextFont
    .top37.tNo65.t0.tex67 insert end text
    vTcl:DefineAlias "$site_4_0.tex67" "combineResult" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tex67 \
        -in $site_4_0 -x 0 -y 0 -width 734 -relwidth 0 -height 154 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo65.t1 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo65.t1" "TNotebook2_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo65 add .top37.tNo65.t1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo65.t1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent42 \
        -in $top -x 117 -y 20 -width 324 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 31 -y 20 -width 64 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 30 -y 60 -width 54 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 117 -y 59 -width 324 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 30 -y 100 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 570 -y 520 -width 87 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 670 -y 520 -width 87 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent60 \
        -in $top -x 119 -y 100 -width 324 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tNo64 \
        -in $top -x 30 -y 140 -width 734 -relwidth 0 -height 166 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tNo65 \
        -in $top -x 30 -y 324 -width 734 -relwidth 0 -height 166 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

